### ISSUE TITLE
useTranslationChange change method returns nothing

### ISSUE THREAD

**Issue by PavPavv** [eolme/i18nano#5]
Why are you using in the change method 'noop' util functions which is actually returns simply empty object. 
...
export const noop = () => { /* Noop */ }
...

I've spent half a day trying to figure out why your so called "examples' from Habr doesn't work. Implementation simply doesn't exist for it. It is almost bare React.Context library doing generally nothing.

**Comment by eolme** [comment]
What do you mean? Did you forget to use the TranslationProvider?
On habr.com an old version and the article is not documentation.

**Comment by PavPavv** [comment]
Yep, you're kinda right. I tried to change it outside of my target page context. Still can't get used to behavior where all functionality only accessible inside the child component from where context is defined. Yet such lines like this:  "export const noop = () => { /* Noop */ }" is really confusing. Anyway thanx, try to continue with your lite lib.
