### ISSUE TITLE
Sync and observe multiple contexts

### ISSUE THREAD

**Issue by PavPavv** [eolme/i18nano#6]
Is there a best approach to handle switching language inside of multiple translations contexts in React? 
According to docs if I want to split translation file into multiple files for every page, I must use asynchronous operations, like async or Promise. But in that case I have to wrap up App component with Suspense component. And if there are plenty of components it is inconvenient to pass prop down the tree every time through every child component (props drilling problem).  I have to create another context or store, which is ok, but when I pass language prop to every TranslationProvider, language prop value do not changing automatically. I have to use useTranslationChange with useEffect. Am I missing something? Or it is ok?

**Comment by eolme** [comment]
Hmmm... well, yes, I guess there is a problem with updating the current language at neighboring providers. I'll look into it soon.
