### ISSUE TITLE
Crash error in React while bundle

### ISSUE THREAD

**Issue by PavPavv** [eolme/i18nano#8]
React build can not be complied after updating to ^4.0.0. lib version. Build crushes with 'Attempted import error: 'use' is not exported from 'react' (imported as 'o').'

**Comment by eolme** [comment]
Which bundler are you using?
Or can you provide a repro link?

**Comment by PavPavv** [comment]
Webpack. But also I tried a fresh blank create-reacr-app (via yarn) test project (https://github.com/PavPavv/i18nano-test) with a few simple examples including next-example from the original repo. It is also failed via building.
